version: '3.9'

services: 
  postgres:
    image: postgres:14-alpine
    ports: 
     - 5434:5432
    volumes:
     - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=todolistUser
      - POSTGRES_DB=todolist
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@dev.dev
      - PGADMIN_DEFAULT_PASSWORD=dev
    ports:
     - 5050:80
volumes:
  pg_data: