@startuml

class Tasks {
    name: string
    description: string
    id_Category: integer
    id_Status: integer
    id_Priority: integer
    deadline: string
    author: string
    ids_Users: integer
}

class Users {
    nickname: string
    email: string
    password: string
}

class Category {
    name: string
}

class Status {
    name: string
}

class Priority {
    name: string
}



Users --o Tasks : create >
Tasks "0..*"--"0..*" Users
Tasks "0..*"--"1" Category
Tasks "0..*"--"1" Status
Tasks "0..*"--"1" Priority


@enduml