@startuml

class Tasks {
    name: string
    description: string
    category: string
    status: integer
    priority: integer
    deadline: string
}

class Users {
    nickname: string
    email: string
}

class Association {
    id_tacks: integer
    id_user: integer
}

Users --o Tasks : create >
Tasks "0..*"--"0..*" Users
Association "0..*"--"0..*" Users

@enduml